### ISSUE TITLE
concept simple requirements should respect member accessibility

### ISSUE THREAD

**Issue by softwareCobbler** [seanbaxter/circle#101]
circle accepts, while msvc / gcc / clang reject the following

```
struct Foo {
private:
    int mfprivate() { return 1; }
public:
    int mfpublic() { return 42; }
};

template<typename T>
concept C = requires(T& foo) {
    foo.mfprivate(); // private member, wouldn't compile
};

auto doit(C auto&& c) {
    return c.mfpublic();
}

int main() {
    return doit(Foo{});
}
```
I was scratching my head at why some of my own code wasn't satisfying a concept like the one above on GCC11; after it became obvious (`-fconcepts-diagnostics-depth=2` ?!) what the problem was I wondered what Circle had to say about it.

**Comment by seanbaxter** [comment]
It's been on my todo list. Will get fixed eventually.
