### ISSUE TITLE
Advice to replace g++ with circle for CMake projects

### ISSUE THREAD

**Issue by correaa** [seanbaxter/circle#105]
Hi, thank you for writing this compiler.

I am wondering if there is a recipe to replace an existing compiler, such as clang++ or g++, in a CMake project.

To switch between g++ and clang++ I do:

```
CXX=clang++  cmake .. -DCMAKE_BUILD_TYPE=Debug     && make
CXX=g++         cmake .. -DCMAKE_BUILD_TYPE=Release  && make
```

However this doesn't work:
```
CXX=/home/user/Download/build_161/circle  cmake .. -DCMAKE_BUILD_TYPE=Debug     && make
```

I get errors in cmake's modules when using `circle`, for example:

```
CMake version: 3.18.4
current build directory: /home/correaa/prj/alf/boost/multi/.build.circle.fast
CMake Warning at /usr/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  test/CMakeLists.txt:20 (find_package)


CMake Warning at /usr/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  test/CMakeLists.txt:20 (find_package)


CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: unit_test_framework serialization) (found
  version "1.74.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
  test/CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/correaa/prj/alf/boost/multi/.build.circle.fast/CMakeFiles/CMakeOutput.log".
See also "/home/correaa/prj/alf/boost/multi/.build.circle.fast/CMakeFiles/CMakeError.log".
```

This is to stress test c++ compliance in my library for multidimensional arrays: https://gitlab.com/correaa/boost-multi

Thank you in advance,
Alfredo

**Comment by samuelpmish** [comment]
I've got some basic CMake/C++ projects working with circle, doing exactly what you describe (idiomatic CMake practice):

```
$ cd /path/to/my_project/build
$ CXX=/path/to/circle cmake ..
$ make -j
```

I tried to build your project with circle, and I get the same issue you posted:

```
$ CXX=/path/to/circle cmake .. 

...

CMake Error at /usr/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: unit_test_framework serialization) (found
  version "1.71.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.21/Modules/FindBoost.cmake:2360 (find_package_handle_standard_args)
  test/CMakeLists.txt:20 (find_package)
```

but this isn't really a `circle` issue, it's just cmake not being able to find boost. If you specify the boost directory explicitly, it can get past those issues. On my machine, `apt` installed boost here:

```
$ CXX=/path/to/circle cmake .. -DBOOST_ROOT=/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/
```

After that, I get more build errors in your project about various dependencies (fftw3 is the next one) not being found, regardless of which C++ compiler I use (tested with gcc, clang, circle). I'm not interested in playing dependency whack-a-mole to get your project building, but hopefully the `BOOST_ROOT` option can get you past your original issue.

Also: consider fixing the build instructions for your repo-- it claims to have zero dependencies, and yet it fails to build unless a lot of dependencies (boost, fftw, blas, lapack, etc) are available!

**Comment by correaa** [comment]
Thank you for your help,

> but this isn't really a `circle` issue, it's just cmake not being able to find boost.

I guess clang++ and g++ help CMake by informing some possible include directories? What is different in "circle"? maybe CMake doesn't recognize the name of the executable to ask about include directories?

> If you specify the boost directory explicitly, it can get past those issues. On my machine, `apt` installed boost here:
> 
> ```
> $ CXX=/path/to/circle cmake .. -DBOOST_ROOT=/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/
> ```

On my machine (Ubuntu 21.10) I have this equivalent directory `/usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/` but I wasn't as lucky. I get the contradictory error: "Could NOT find Boost (missing: unit_test_framework serialization) (found
  version "1.74.0")"

```
$ CXX=/home/correaa/Downloads/build_166/circle cmake .. -DBOOST_ROOT=/usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/
CMake version: 3.18.4
current build directory: /home/correaa/prj/alf/boost/multi/.build.circle.fast
CMake Warning at /usr/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  test/CMakeLists.txt:20 (find_package)


CMake Warning at /usr/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  test/CMakeLists.txt:20 (find_package)


CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: unit_test_framework serialization) (found
  version "1.74.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
  test/CMakeLists.txt:20 (find_package)
```

 
> After that, I get more build errors in your project about various dependencies (fftw3 is the next one) not being found, regardless of which C++ compiler I use (tested with gcc, clang, circle). I'm not interested in playing dependency whack-a-mole to get your project building, but hopefully the `BOOST_ROOT` option can get you past your original issue.
> 
> Also: consider fixing the build instructions for your repo-- it claims to have zero dependencies, and yet it fails to build unless a lot of dependencies (boost, fftw, blas, lapack, etc) are available!

Well, for using the core of the library `include/multi/array.hpp` you don't need any dependency.

The dependency on Boost.Test is for running the tests only (not sure if that is a real dependecy).
The dependency on Boost.Serialization, fftw, blas, lapack is for the "adaptors" part of the library. 
Maybe I will not test these if the dependency is not found in test, or move these adaptors to a separate accessory library (`multi-adaptors`).

At the moment I will clarify this in the text. (https://gitlab.com/correaa/boost-multi/-/tree/master#dependecies-and-compiler-requirements)

It would be great to have the library compiled with Circle. So far I made it compile with almost any C++17 compiler around, gcc, clang, intel classic, intel one-api, nvcc, nvc++, (pgi at some point), not sure I am missing one.

**Comment by correaa** [comment]
Thank you for your help. 

After trying many things (from the links and beyond), this is what worked for me in Ubuntu 21.10: adding explicitly the Boost Lib dir.

```
CXX=/home/correaa/Downloads/build_166/circle cmake .. -DBOOST_LIBRARYDIR=/usr/lib/x86_64-linux-gnu/ -DENABLE_CIRCLE=1
```

This (accidentally) also fixed the detection of other libraries mentioned.

Now, of course, I have regular compilation errors with circle that I will ask about in separate issues.

Also, I had to add the `ENABLE_CIRCLE` option to disable the CMake code that was adding warnings no recognized by circle.
CMake was detecting circle as either `CXX_COMPILER_ID:GNU` or `CUDA_COMPILER_ID:Clang`

for example, this was the generated command:
```
cd /home/correaa/prj/alf/boost/multi/.build.circle/test && /home/correaa/Downloads/build_166/circle  -I/home/correaa/prj/alf/boost/multi/include -isystem /usr/include --stdlib=libc++ -Werror -Wall -Wextra -Wcast-align -Wcast-qual -Wconversion -Wdouble-promotion -Wformat=2 -Wmissing-include-dirs -Wno-unknown-pragmas -Wnon-virtual-dtor -Wnull-dereference -Wmove -Wold-style-cast -Woverloaded-virtual -Wpointer-arith -Wpedantic -Wredundant-decls -Wshadow -Wsign-conversion -Wstrict-aliasing -Wswitch-enum -Wuninitialized -Wunused -Wunused-result -Wzero-as-null-pointer-constant -o CMakeFiles/zero_dimensionality.cpp.x.dir/zero_dimensionality.cpp.o -c /home/correaa/prj/alf/boost/multi/test/zero_dimensionality.cpp
circle: Unknown command line argument '-Wcast-align'.  Try: '/home/correaa/Downloads/build_166/circle --help'
circle: Did you mean '--stdlib'?
circle: Unknown command line argument '-Wcast-qual'.  Try: '/home/correaa/Downloads/build_166/circle --help'
circle: Did you mean '--stat'?
```

Please let me know if you have a better way to make CMake detect the compiler as an alternative.

(in `test/CMakeLists.txt`)
```
	if(NOT DEFINED ENABLE_CIRCLE)
		target_compile_options(
			${TEST_EXE}
			PRIVATE
$<$<AND:$<CXX_COMPILER_ID:GNU>,$<NOT:$<CUDA_COMPILER_ID:NVIDIA>>,$<NOT:$<CUDA_COMPILER_ID:Clang>>>:
					-Werror
					-Wall
					-Wextra
					-Wcast-align
				>
				$<$<CXX_COMPILER_ID:Intel>:  # also IntelLLVM, XL (ibm), XLClang (ibm)
					-Werror
					-Wall
					-Wextra
					-diag-disable=remark
				>
		)
	endif()
```

**Comment by correaa** [comment]
Some seemly trivial warnings actually revealed some bugs, for example (in my code) header guards that had inconsistent typos. 

This is a table of warnings and the reason I disabled them.

```
#  -altera-id-dependent-backward-branch,                  // seems like a buggy warning https://github.com/llvm/llvm-project/issues/52790
#  -altera-struct-pack-align,                             // this asks to use non-standard pragmas such as __attribute__((aligned(0))) and _attribute__((packed)), may interfeere with gcc/nvcc compatibility?
#  -altera-unroll-loops,                                  // BOOST_REQUIRE macro requires this, asks for pragmas
#  -cert-err58-cpp,                                       // BOOST_AUTO_TEST_CASE macro requires this
#  -cppcoreguidelines-avoid-magic-numbers,                // all tests use magic numbers, ok for other sources
#  -cppcoreguidelines-avoid-non-const-global-variables,   // BOOST_AUTO_TEST_CASE macros require this
#  -cppcoreguidelines-macro-usage,                        // BOOST_TEST_MODULE macro requires this
#  -cppcoreguidelines-pro-bounds-array-to-pointer-decay,  // assert macros need this
#  -cppcoreguidelines-pro-type-vararg,                    // BOOST_REQUIRE macros require this
#  -fuchsia-default-arguments-calls,                      // BOOST_REQUIRE macros require this
#  -fuchsia-overloaded-operator,                          // this library overloads operators (==, >, +)
#  -fuchsia-statically-constructed-objects,               // BOOST_AUTO_TEST_CASE creates these
#  -fuchsia-trailing-return,                              // to allow any '-> decltype(auto)'
#  -hicpp-vararg,                                         // all BOOST_TEST_REQUIRE macros require this
#  -hicpp-no-array-decay,                                 // all assert macros require this
#  -llvmlibc-implementation-in-namespace,                 // nonsense warning
#  -llvmlibc-callee-namespace,                            // nonsense warning
#  -llvmlibc-restrict-system-libc-headers,                // nonsense warning
#  -modernize-use-nodiscard,                              // this would add [[nodiscard]] to almost all functions, adding a lot of noise
#  -readability-magic-numbers,                            // all tests use magic numbers, ok for other sources
```
