### ISSUE TITLE
extern __shared__ array causes segmentation fault

### ISSUE THREAD

**Issue by jaredhoberock** [seanbaxter/circle#106]
The program

```
extern __shared__ int x[];

int main()
{
  return 0;
}
```

Causes circle to segmentation fault:

```
$ circle --cuda-path=/usr/local/cuda -sm_70 repro.cu 
Segmentation fault (core dumped)
```

Compiler details:

```
$ circle --version
circle version 1.0.0-162
  Circle public preview build 162
  Built Mar 12 2022 19:09:24
  (c) 2022 Sean Baxter
  https://www.circle-lang.org/
  Twitter: @seanbax
```

**Comment by seanbaxter** [comment]
Obv the segfault is unacceptable, but is this something we should support?
```cpp
#include <cuda_runtime_api.h>

__global__ void kernel(int* p) {

  extern __shared__ int x[];
  
  x[threadIdx.x] = threadIdx.x + 1;
  __syncthreads();
  
  int y = x[(threadIdx.x- 1) & 31];
  __syncthreads();

  p[threadIdx.x] = y;
}

int main() {
  kernel<<<1,1,16384, nullptr>>>(nullptr);
  return 0;
}
```

Declaring the shared array in the kernel makes it clear what it is. I'm not sure what the meaning of declaring it externally is. I know nvcc supports that, but with a multi-pass translation model, that declaration isn't even processed by the host pass.

**Comment by jaredhoberock** [comment]
What does your code example demonstrate?

**Comment by seanbaxter** [comment]
That you can do `extern __shared__ int x[];` inside a kernel and it works. Is putting that declaration in namespace scope a practice that should continue?

**Comment by jaredhoberock** [comment]
I don’t know. But a variable in the global scope can be accessed by more than one function, which is what my use case requires.

**Comment by seanbaxter** [comment]
Fixed for the next build so that it works like it does in nvcc.

As far as a builtin, that seems easy enough, as internally it would just declare an `extern __shared__` array and return an lvalue to that. TBH maybe using a global variable template is the way:
```cpp
template<typename type_t>
extern __shared__ type_t shared_dynamic_array[]; 
```

Then do `shared_dynamic_array<float>` or whatever, from anywhere, to use it.
