### ISSUE TITLE
friend injection never injected

### ISSUE THREAD

**Issue by DaemonSnake** [seanbaxter/circle#109]
Hi!
Friends injection (separation of friend declaration and friends definition via template) doesn't work with CircleC++
Take the following example:
```c++
struct flag {
    friend int initialize(flag); //causes "initialize" to be declared
};

template<class FinalT>
struct final_writer {
    friend int initialize(flag) {
        return 0;
    }
};

int main() {
    auto x = initialize(flag{});
}

final_writer<int> tmp = {}; //causes "initialize" to be defined
```
The following example compiles and runs correctly in all major compilers: https://godbolt.org/z/G39qcKEhY

But the definition never occurs in CircleC++: https://godbolt.org/z/zT1ed9hP6

**Comment by seanbaxter** [comment]
Fixed for the next build.
