### ISSUE TITLE
Macro to detect compilation with Circle

### ISSUE THREAD

**Issue by correaa** [seanbaxter/circle#113]
Is there a macro to detect that source is being compiled with Circle?

Such as `__clang__` for clang.

Sorry if I missed it from the documentation/website.

**Comment by jaredhoberock** [comment]
It's `__circle_lang__`.

**Comment by correaa** [comment]
Got it, 

```
circle -dM dummy_source.cpp | grep circle
#define __circle_build__ 166
#define __circle_libstdcxx 
#define __clang_version__ "circle 1.0"
#define __circle_lang__ 
#define __circle_major__ 1
#define __circle_minor__ 0
```

@jaredhoberock ,  I guess I will use `__circle_build__` to detect Circle as a _compiler_ and `__circle_lang__` if I am interested in the language.
