### ISSUE TITLE
?? operator: "ip: eval of expr_dep_tparam_ref_t not implemented"

### ISSUE THREAD

**Issue by samuelpmish** [seanbaxter/circle#116]
Hi, I just learned about operator `??` from your recent tweet and was wondering if it could replace this awful construction that shows up in conventional C++ more than I'd like:

```cpp
  constexpr int i = ...;
  auto z = [](){
    if constexpr (i < 20) {
        return foo{};
    } else {
        return bar{};
    }
  }();
```
by 
```cpp
constexpr int i = ...;
auto z = (i < 20) ?? foo{} : bar{}; // much nicer!
``` 
but the first attempt produced the error message in the title: https://godbolt.org/z/nKWThnh67

Is it still a requirement that the different branches of the constexpr ternary have the same type?

**Comment by seanbaxter** [comment]
Hi, I was ignoring github issues as I was working on my conference talk. But now that's done, I check this one out, and it looks like it works in the current build 170:
https://godbolt.org/z/hMGYjc41n

Can you confirm it does what you want?

**Comment by seanbaxter** [comment]
If you want your mind blown, try writing it this way:
https://godbolt.org/z/46bnGajqG

The ::? operands can be types (or templates, or variable templates, or concepts or universals). So you can do a conditional to produce a type, then instantiate an instance of that with the postfix { }.

**Comment by samuelpmish** [comment]
Yes, things seem to be working now! 

This is a great feature, and I really liked your godbolt example. The postfix also works with nontrivial constructors too,

```cpp
#include <iostream>
#include <cstdio>

struct foo{
    foo (int) {
        printf("making a foo\n");
    }
};
struct bar{ 
    bar (int) {
        printf("making a bar\n");
    }
};

template < int i >
auto func() {
  auto z = (i < 20 ?? foo : bar)(3);
  return z;
}

int main() {
  foo x = func<5>(); 
  bar y = func<25>();
}
```

very nice
