### ISSUE TITLE
Default template parameter expression too complex to parse?

### ISSUE THREAD

**Issue by LapysDev** [seanbaxter/circle#135]
The following works as expected: <a href="https://lapys.godbolt.org/z/hb68fode3" target="_blank">https://lapys.godbolt.org/z/hb68fode3</a>
```cpp
template <typename base, base>
struct constant {};
```
```cpp
template struct constant<int,  0>;
template struct constant<int*, nullptr>;

/* and so on… */
```
&mdash; defining the `constant` `template struct` with specified types and their corresponding constants.
Taking things further, a `nil` `template struct` is defined to provide a null constant for arithmetic, boolean, character, and pointer types: <a href="https://lapys.godbolt.org/z/EaasqEPsd" target="_blank">https://lapys.godbolt.org/z/EaasqEPsd</a> _(see current implementation: <a href="https://gist.github.com/LapysDev/a74d9700817652682370e75312f67034" target="_blank">https://gist.github.com/LapysDev/a74d9700817652682370e75312f67034</a>)_
```cpp
template <typename base>
struct nil {
  constexpr static value = 0;
};

template <typename base> // and other pointer variations
struct nil<base*> {
  constexpr static value = nullptr;
};

/* — and other `nil` specializations, including `std::nullptr_t`, function pointers, etc… */
```
With this trait, `constant` could be used more generically on any type that `nil` supports, like so
```cpp
template struct constant<int,  nil<int> ::value>;
template struct constant<int*, nil<int*>::value>;

/* and so on… */
```
&mdash; but this could be more concise if the user only just required a null constant, hence the **default template parameter**:
```cpp
template <typename base, base = nil<base>::value>
struct constant {};
```
Problem with this though is that it seems to only work with non-qualified types.
The code compiles and executes normally on the Clang, GCC, ICC, and MSVC C++ compilers:
<a href="https://lapys.godbolt.org/z/34Yf7f597" target="_blank">https://lapys.godbolt.org/z/34Yf7f597</a>

but fails with this error at the core of the problem:
<a href="https://lapys.godbolt.org/z/W9fqdsr8a" target="_blank">https://lapys.godbolt.org/z/W9fqdsr8a</a>
```
unexpected template argument expression
```
which is raised when the instantiation is evaluated, the `template` definition with the default argument by itself is otherwise fine

**Comment by seanbaxter** [comment]
Fixed for the next release. Thanks for reporting.
