### ISSUE TITLE
`let` keyword not working

### ISSUE THREAD

**Issue by AbhinavK00** [seanbaxter/circle#151]
Under `#pragma feature edition_carbon_2023`, the `let` keyword to declare constants does not work and keyword `const` also gives a compile time errors.

Following is the error given when using `let` keyword: 
```
undeclared identifier 'let'
  let x := 3;
  ^
```

And this is the error given when using `const` keyword:
```
expression-statement names a type; did you intend a declaration?
  const auto y = 4;
  ^
```
And when sticking to a specific type:
```
cv-qualifier found without type-specifier
  const int32_t a = 0;
  ^
```

*small suggestion*
`var x := 4;` declares a variable with inferred type. Maybe instead of let or const, you can do -
`x := 4;` to declare constants, so as the programmer declares constants by default if not specified. This behaviour is similar to rust and was also proposed for cppfront.

**Comment by AbhinavK00** [comment]
Proposal: Modern Syntax for declaring constants
The `let` keyword will be the modern counterpart to `var` keyword currently used to declare variables in circle under the pragma feature "carbon_edition_2023".

Following is the new syntax along with its corresponding old cpp syntax
```
NEW SYNTAX                                                                          OLD SYNTAX
let a := 3;                                                                         const auto a = 3;
let a : T = 4;                                                                      const T a = 3;
```

Alternative considered:
One alternative considered is not having a keyword and having bindings be constant by default.

Following is the new syntax along with its corresponding old cpp syntax
```
NEW SYNTAX                                                                      OLD SYNTAX
a := 3;                                                                         const auto a = 3;
a : T = 4;                                                                      const T a = 3;
```

Hope this is enough ;)

**Comment by mingodad** [comment]
I'm not sure removing the keyword is a good idea, the keyword gives a clear visual indication of a new declaration.

**Comment by realgdman** [comment]
Under carbon2023, it can be written as `var x: const int = 3;`
