### ISSUE TITLE
Output C++

### ISSUE THREAD

**Issue by blockspacer** [seanbaxter/circle#2]
Can circle output C++ code?

**Comment by seanbaxter** [comment]
I've been working on that, from time to time. It's very hard to emit C++ code, but I have made some progress. It's something I'll return to.

**Comment by kdkavanagh** [comment]
Curious if you've made progress on this or have more thoughts? Due to some esoteric restrictions/configurations, I need to build the resulting code with a very specific compiler, but would love to use the metaprogramming circle offers as a replacement for cpp macros.

**Comment by seanbaxter** [comment]
It's not something on the front burner. I think source-to-source translation won't actually be a good user experience. With time it will come, but it's not a priority.
