### ISSUE TITLE
C support (Perhaps opening the integration test suite?)

### ISSUE THREAD

**Issue by chadbrewbaker** [seanbaxter/circle#22]
Is there any reason a subset of Circle cannot output valid C code? Perhaps a meta_c@ to emit compile-time evaluations that are correct C? Probably need this anyway for metas that must be in older C++ versions or avoid the use of the STL.

Probably quickest to blast test suite code with clang to see if there are errors and if so pass through clangAST to describe known C++ AST elements that are illegal in C?

When I ported Ruby 1.8 to Blue Gene/L, having the test suite was 100x more helpful than the documentation. You might consider opening an integration test suite, https://www.cs.princeton.edu/courses/archive/spring01/cs333/awktest.html

**Comment by seanbaxter** [comment]
Emitting C code, it's possible, it would be time consuming. I'm not sure the output would be something people would want to look at or use. I think if I get funding and support that would be something to add, but it's not a priority for me right now.
