### ISSUE TITLE
Is there a way to emit assembly with Intel syntax? (aka pass --x86-asm-syntax=intel to llvm)

### ISSUE THREAD

**Issue by thedmd** [seanbaxter/circle#24]
I'm toying with circle in compiler-explorer and I'm looking for a way to emit Intel syntax assembly output.
I checked every corner of the docs I can find already, last thing I can do I to ask.
Is there a switch I can use to do that?

**Comment by seanbaxter** [comment]
There isn't yet. That's a good idea. I'll add it to an upcoming version.

**Comment by seanbaxter** [comment]
I implemented `--x86-asm-syntax=intel` and it'll go out with the next binary. Thanks for the suggestion.

**Comment by thedmd** [comment]
Thank you!
