### ISSUE TITLE
Build 128: Segmentation fault while compiling mandelbrot example

### ISSUE THREAD

**Issue by thedmd** [seanbaxter/circle#25]
Something goes wrong when I try to execute `mandelbrot` function at compile time.
It is related to `<complex>`. Compiler does not output any helpful message.
```
./circle mandelbrot.cxx
Segmentation fault
```

[This is expected output](https://godbolt.org/z/c96eMx74b) with handcrafted `complex` class.

[This is how it run](https://godbolt.org/z/vbeErWb8T) with `std::complex<>`.

`mandelbrot.cxx`
```cpp
/// Adapted from wes' code. <https://web.archive.org/web/20210411041036/http://www.fractalforums.com/programming/mandelbrot-with-only-18-lines-of-cplusplus-code!/>
#include <cstdio>
#include <complex>

static void mandelbrot()
{
    using namespace std;
    constexpr auto kRows = 22, kCols = 78, kRuns = 20;

    for (float x: @range(kRows + 1)...)
    {
        for (float y: @range(kCols - 1)...)
        {
            complex<float> z, c { y * 2 / kCols - 1.5f, x * 2 / kRows - 1.0f };
            auto i = 0;
            while (abs(z) < 2 and ++i < kRuns)
                z = pow(z, 2.0f) + c;
            putchar(i != kRuns ? '.' : '#');
        }
        putchar('\n');
    }
}

int main()
{
    @meta mandelbrot();
    mandelbrot();
}
```

**Comment by seanbaxter** [comment]
Thanks. Will fix it and get it in with the new binary this week.

**Comment by seanbaxter** [comment]
By the way, no need to write @range like that.
```cpp
for(float x : kRows + 1)  { }
```
is all you need. 

The `@range()` is for generating a parameter pack. In a ranged-for it's also useful because it gives you python-style slices, so you can choose an offset and step.

**Comment by thedmd** [comment]
I didn't know that. Managed to try all complicated solutions and never thought of the simplest one.
Thanks!

**Comment by seanbaxter** [comment]
Awesome. The meta interpreter was entirely lacking in C99 _Complex capability, which is why std::complex failed. Added that and your sample works fine. Will go out with the new binary this week. Thanks.

![Screenshot at 2021-07-26 19-21-03](https://user-images.githubusercontent.com/521513/127071403-50885ec6-7fcc-40b6-9255-c0292aee15ba.png)
