### ISSUE TITLE
Upgrade godbolt to libstdc++10

### ISSUE THREAD

**Issue by seanbaxter** [seanbaxter/circle#27]
Hey @thedmd, is it possible to upgrade the godbolt circle to libstdc++10? I'm not sure why it is only finding 9. I've tried -libstdc++=10 which fails.

**Comment by thedmd** [comment]
I will look into that.

**Comment by thedmd** [comment]
There is a gcc-10 instance installed on `/opt/compiler-explorer/gcc-10.3.0`.
We tried to use it the clang way by passing `--gcc-toolchain=/opt/compiler-explorer/gcc-10.3.0`. Such command isn't supported.
Passing `--isystem=/opt/compiler-explorer/gcc-10.3.0` compile but still link version 9.
My guess is, circle is looking for libstdc++ in hardcoded `/usr/lib/gcc/x86_64-linux-gnu/<version>/` path.

Is it possible to have switch similar to `--gcc-toolchain`?

**Comment by seanbaxter** [comment]
I only just found out about `--gcc-toolchain`. I'll definitely add support for that. And ya, circle is looking for libstdc++ in like 7 different hard-coded paths to cover different linux distributions. I think `--gcc-toolchain` will fix this.

**Comment by thedmd** [comment]
Would you like libstdc++10 to be default value?
I can later make a PR to CE which pass `--gcc-toolchain` pointing to v10.

**Comment by seanbaxter** [comment]
I don't think setting `-libstdc++=10` right now will work, because it can't find it. Definitely I need 10 (for C++20 stuff) but I think `--gcc-toolchain` has to be implemented to make that work on CE.

**Comment by seanbaxter** [comment]
When you have some time could you give this a spin?
https://circle-lang.org/linux/build_gcc_toolchain.tgz

Basically, `circle -gcc-toolchain=/usr -libstdc++=10 foo.cxx` is default on my system. Haven't really tested this because it is a pain to install an all new gcc. But I bet it works. :)

It does assume that under the toolchain path there are folders like `include/c++/{version}/` and corresponding ones for binaries. There are no docs for how this should work so I am just checking all the paths that I do to support debian/fedora/rhel/arch.

**Comment by thedmd** [comment]
CE has prebuild gcc version stored on S3. For example 10.3.0 can be downloaded from:
<https://s3.amazonaws.com/compiler-explorer/opt/gcc-10.3.0.tar.xz> which is installed to `/opt/compiler-explorer/gcc-10.3.0`.

Apparently in standalone build full version is used, there is `include/c++/10.3.0`. Libs are found in:
```
/opt/compiler-explorer/gcc-10.3.0/lib64/libstdc++.so
/opt/compiler-explorer/gcc-10.3.0/lib64/debug/libstdc++.so
/opt/compiler-explorer/gcc-10.3.0/lib32/libstdc++.so
/opt/compiler-explorer/gcc-10.3.0/lib32/debug/libstdc++.so
/opt/compiler-explorer/gcc-10.3.0/libx32/libstdc++.so
/opt/compiler-explorer/gcc-10.3.0/libx32/debug/libstdc++.so
```

Running this did not worked:
```bash
./circle sanity.cxx -O3 --gcc-toolchain=/opt/compiler-explorer/gcc-10.3.0 --libstdc++=10
preprocessor: sanity.cxx:1:10
cannot find header cstdio
```

When I provide full `10.3.0` version, c++ headers were found, but internal bits were not:
```bash
./circle sanity.cxx -O3 --gcc-toolchain=/opt/compiler-explorer/gcc-10.3.0 --libstdc++=10.3.0
preprocessor: /opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/cstdio:41:10
... included from sanity.cxx:1:10
cannot find header bits/c++config.h
```

They are here and are architecture dependent:
```bash
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/x86_64-linux-gnu/x32/bits/c++config.h
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/x86_64-linux-gnu/32/bits/c++config.h
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/x86_64-linux-gnu/bits/c++config.h
```

Looking at [how clang does it](https://github.com/llvm-mirror/clang/blob/aa231e4be75ac4759c236b755c57876f76e3cf05/lib/Driver/ToolChains/Gnu.cpp#L1759), there is no one size that fits all.

**Comment by seanbaxter** [comment]
Ahhh pre-built gcc I'll install that and keep trying. Thanks

**Comment by seanbaxter** [comment]
I refreshed 
https://circle-lang.org/linux/build_gcc_toolchain.tgz

It compiles all my tests except boost.stacktrace which requires backtrace.h which is apparently not part of the GCC binary distribution, but is in the git repo and comes on some distributions. But I think this means it works right, since gcc and clang on CE also fail to access this file.

Thanks for your help Michal.

**Comment by thedmd** [comment]
Sure, no trouble.

I tested new build locally and it is working as expected.

libbacktrace probably can be added as a library that can be enabled in 'Libraries' menu. I need to investigate that. No promises on ETA, next few days will be busy.

Will this be in 131 release? I can make a PR to automatically point `--gcc-toolchain` to gcc for 131 and newer versions. If Matt already didn't decided to do that.

**Comment by seanbaxter** [comment]
No reason to investigate libbacktrace. It's just an oddity of how GCC packages their stuff.

Yes this will be in 131 and all version going forward.

**Comment by thedmd** [comment]
Build 131 is live on CE. This one and `Latest` use `--gcc-toolchain` pointing to 10.3.0.
![image](https://user-images.githubusercontent.com/1197433/131990324-98f06b2c-8f8c-4106-947b-c0135f0749dc.png)
