### ISSUE TITLE
circle: "Undeclared identifier 'is_same_v'" when #include <array>

### ISSUE THREAD

**Issue by jaredhoberock** [seanbaxter/circle#30]
The program:

```
#include <array>

int main()
{
  return 0;
}
```

Yields the following compiler error message:

```
$ ~/Desktop/circle/circle -std=c++14 repro.cpp 
error: /usr/include/c++/9/array:245:29
... included from repro.cpp:1:10
undeclared identifier 'is_same_v'
      -> array<enable_if_t<(is_same_v<_Tp, _Up> && ...), _Tp>, 
```

**Comment by seanbaxter** [comment]
Don't use -std=c++14. Circle defaults to 17, and is_same_v is 17. I don't know what's up with that header. It probably detected the concepts capability macro and used is_same_v.

**Comment by jaredhoberock** [comment]
I will use -std=c++17 as a workaround, but it's worth understanding what is going wrong with this issue.

The use of `is_same_v` is guarded in `<array>` by `__cpp_deduction_guides`:

```
#if __cpp_deduction_guides >= 201606
  template<typename _Tp, typename... _Up>
    array(_Tp, _Up...)
      -> array<enable_if_t<(is_same_v<_Tp, _Up> && ...), _Tp>,
	       1 + sizeof...(_Up)>;
#endif
```

And it seems like `__cpp_deduction_guides` is indeed defined in the following program:

```
#include <iostream>

int main()
{
  @meta std::cout << "__cpp_deduction_guides: " << __cpp_deduction_guides << std::endl;
}
```

```
$ circle -std=c++14 repro.cpp 
__cpp_deduction_guides: 201611
```

Is it possible that circle enables deduction guides with `-std=c++14` when it shouldn't?

**Comment by seanbaxter** [comment]
Fixed. I am now gating capability macros by `__cplusplus` version. Will be in build 133.
