### ISSUE TITLE
make opensource or crowdfund

### ISSUE THREAD

**Issue by blockspacer** [seanbaxter/circle#4]
I hope project will find support (patreon, maybe?) or become opensource, otherwise it will be risky to use with big production code bases.

**Comment by stefanos82** [comment]
@blockspacer Based on the official website it's licensed under [1-clause BSD License](https://www.circle-lang.org/#license).

You can compare it with the [actual license itself](https://spdx.org/licenses/BSD-1-Clause.html).

I guess @seanbaxter needs to make it more explicit in main page?

**Comment by blockspacer** [comment]
> @blockspacer Based on the official website it's licensed under [BSD 1-Clause License](https://www.circle-lang.org/#license).
> 
> You can compare it with the [actual license itself](https://spdx.org/licenses/BSD-1-Clause.html).
> 
> I guess @seanbaxter needs to make it more explicit in main page?

I can find neither circle source code (only a lot of examples) nor `donate` button.

**Comment by stefanos82** [comment]
Very true.

I have realized that after I tried to find out how to compile circle itself. I guess @seanbaxter has to clarify this so we know whether we should take this seriously or not.

**Comment by aldanor** [comment]
> I hope project will find support (patreon, maybe?) or become opensource, otherwise it will be risky to use with big production code bases.

Ditto, a very interesting project but no serious company would ever allow this to touch their internal codebases unless the code is open source and/or reviewed by the community - which is sad.
