### ISSUE TITLE
circle: "unsupported attribute on declaration" upon use of __managed__

### ISSUE THREAD

**Issue by jaredhoberock** [seanbaxter/circle#48]
The program

```
__managed__ int result;

int main()
{
  return 0;
}
```

Causes circle to emit the error message

```
$ circle --cuda-path=/usr/local/cuda -sm_50 repro.cu 
error: repro.cu:1:17
unsupported attribute on declaration
__managed__ int result; 
                ^
```

Compiler details:

```
$ ~/Desktop/circle/circle --version
circle version 1.0.0-136
  Circle public preview build 136
  Built Sep 27 2021 23:42:52
  (c) 2021 Sean Baxter
  https://www.circle-lang.org/
  Twitter: @seanbax
```

**Comment by seanbaxter** [comment]
I don't have the bandwidth to implement CUDA managed memory at this point. The docs are very sketchy. I will revisit this in the future.

**Comment by jaredhoberock** [comment]
What additional information is necessary?

**Comment by seanbaxter** [comment]
For `__managed__` variables, I'm pretty sure you need to register a correspondence between the host address and PTX declaration. I already do this for normal `__device__` objects and for kernels `__cudaRegisterFunction`. This is part of `__cudaRegisterFatBinary` ninjitsu. It's these registrations that support conveniences like `cudaMemcpyFromSymbol`. 

But the calls are undocumented, so I'd need to create more test cases and run nvcc with -keep to keep the temporaries, then reverse engineer the cruft it leaves. I'm just slammed with stuff trying to get my windows target working, and the context switch to nvcc reverse engineering is not what I should be doing right now.

**Comment by seanbaxter** [comment]
Jared, are `__managed__` variables in your critical path? If so, that can change my priorities.

**Comment by jaredhoberock** [comment]
I appreciate your explaining what your current priorities are.

I have mixed feelings about `__managed__` variables. I use them in all of my unit tests because they are a convenient way to establish a communication channel between CPU and GPU for simple exchanges.

On the other hand, I originally argued against their existence because they can only be used on global variables. So I never use them in production code bases. Also, I noticed that `clang` does not implement support for them.

Before I argue strongly for `__managed__` support, I'd like to discover any remaining issues in this code I'm triaging.

For example, if this issue is the last one, I think you should just go ahead and build support for `__managed__` and then you can argue that you have reasonably complete CUDA support. But there could be other more fundamental missing features that ought to take priority over `__managed__`. I'd like to rule out that possibility in the next few days.

**Comment by seanbaxter** [comment]
The other thing I haven't attempted is Cuda Dynamic Parallelism. Another case of something with no documentation. Is that useful to you?

**Comment by jaredhoberock** [comment]
CDP is a nice-to-have feature. I doubt it's actually used in production. I tend to implement support for CDP when it is available, and ignore it when it isn't.

**Comment by jaredhoberock** [comment]
After going through the rest of my unit tests, it seems like `__managed__` is the last significant piece of missing CUDA support that my code bases require.
