### ISSUE TITLE
[Question]  How ? What next ?

### ISSUE THREAD

**Issue by redradist** [seanbaxter/circle#59]
## How ?
I am amazed that in 2021 one person was able to create the whole compiler from scratch (even it is a front-end compiler) ...

I see that main branch has on 250 commits (30.10.2021) !!
How it is possible to implement the whole compiler for C++ only for 250 commits ? Is it fully support C++20 standard ?!

Also I want to thank you about this implementation, it is very inspiring, it proves that even single person if it has an inspiration and free time can write such complex code like front-end compiler for C++ with all C++ complexity and corner cases ...

## What next ?
Is it production ready ? Do you plan to make it production ready ?

**Comment by seanbaxter** [comment]
> Is it production ready ?
I'm doing my best. But am going to need corporate support to make people confident that it will be around for the ages.
