### ISSUE TITLE
Integration with Compiler Explorer

### ISSUE THREAD

**Issue by thedmd** [seanbaxter/circle#6]
Hello @seanbaxter 

Did you consider putting circle compiler on Compiler Explorer? That should boost visibility and allow people play with compiler more easily.

**Comment by seanbaxter** [comment]
There was an issue before where the Compiler Explorer instance was built with an older version of libstdc++. I require a pretty recent version, due to a dependency on <filesystem>. However, I'm told CE was recently updated to Ubuntu 20.04 and Matt and people are looking at putting Circle on there.

**Comment by thedmd** [comment]
@seanbaxter Circle is now available in Compiler Explorer (https://godbolt.org/z/aebjYfonY).
![image](https://user-images.githubusercontent.com/1197433/126938885-4f71c9a5-d861-4f7b-a2f5-23b68d172c95.png)

**Comment by thedmd** [comment]
Circle is live on CE. I think I can close this now.
