### ISSUE TITLE
CPU arch support for ARMv8 or newer (aarch64)

### ISSUE THREAD

**Issue by jenisys** [seanbaxter/circle#66]
I am just curious:
Is any support of the ARMv8/ARMv9 architecture planned (or in the works or already supported) ?

NOTE: Currently, only Intel x86_64 CPU architecture (for Linux/UNIX) is supported (while Windows support is in the backlog until the C++ ABI specs are available) by reading the READMEs/docs/issues.

**Comment by seanbaxter** [comment]
ARM would be awesome, but I'm a one-man unfunded operation and don't have the resources to deploy for other targets right now. Definitely want to do it when it's possible!
