### ISSUE TITLE
Question/Feature/Discussion : smart pointers as language features

### ISSUE THREAD

**Issue by pfeatherstone** [seanbaxter/circle#78]
How about having smart pointers as part of the language, not the standard library?
If they were part of the language you could make it such that the following were impossible:
- references to smart pointers
- pointers to smart pointers
- smart pointers to smart pointers
Because smart pointers are part of the library, there is nothing stopping you from doing any of these. Maybe there is some template/concept magic that would, but treating smart pointers on the same footing as references and raw pointers as far as the language is concerned would make things clearer. You could argue that lvalue and rvalue references are also smart pointers... So one can argue that they should all be treated the same.

**Comment by seanbaxter** [comment]
I think the bigger value add would be to implement a "relocate" semantic, like move semantics but with the transference of ownership. And that, I think, implies a new reference type to carry relocation information through function calls. 

For smart pointers specifically, there could be language porcelain for std::unique_ptr, but I don't know about extending it to all the kinds of smart pointers people use. It's not obvious what should be done with that.
