### ISSUE TITLE
Overload set

### ISSUE THREAD

**Issue by j8asic** [seanbaxter/circle#80]
Can non-specialized template functions or set of overloaded functions be passed as template arguments? Something like [std::overload_set](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1170r0.html)

**Comment by seanbaxter** [comment]
They can't. Is there a current proposal for that functionality? If it's still living I may do it.

**Comment by seanbaxter** [comment]
Procedure cloning you describe is a part of the core Circle language.
https://godbolt.org/z/TojMqThzx

If you want n-dimensional dispatch support and more options, try __visit:
https://github.com/seanbaxter/circle/tree/master/variant#visit

**Comment by j8asic** [comment]
Ohh `call_f` is very nice way to manually connect runtime param to the correct template call. But it is handy for only one param, and still a manual operation. I was thinking more if the compiler could automatically clone a hot function and introduce `call_f` behind the scenes?

**Comment by seanbaxter** [comment]
Look at the __visit mechanism. It does any number of parameters.

**Comment by seanbaxter** [comment]
Closing for now. Have no specific plans for adding overload sets as a language feature.
