### ISSUE TITLE
Cannot find option named 'gnu++14'

### ISSUE THREAD

**Issue by tksuoran** [seanbaxter/circle#81]
Attempt to compile lunasvg with CMake 3.22.2 gives this error:

```
circle  -Iinclude -Isource -I3rdparty/software -I3rdparty/plutovg -g -std=gnu++14 -MD -MT lunasvg.cpp.o -MF lunasvg.cpp.o.d -o lunasvg.cpp.o -c source/lunasvg.cpp
circle: for the --std option: Cannot find option named 'gnu++14'!
```
```
$ cmake --version
cmake version 3.22.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
I examined the `CMakeLists.txt` files of the project and they look clean, only doing `set(CMAKE_CXX_STANDARD 14)` which I assume is the cause:

CMake documentation https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD says

> This property specifies the C++ standard whose features are requested to build this target. For some compilers, this results in adding a flag such as -std=gnu++11 to the compile line. For compilers that have no notion of a standard level, such as Microsoft Visual C++ before 2015 Update 3, this has no effect.

**Comment by tksuoran** [comment]
Both `set(CMAKE_CXX_STANDARD 11)` and `set(CMAKE_CXX_STANDARD 17)` have similar issue.

After removing this `CMAKE_CXX_STANDARD` setting, compilation proceeds a bit further, but fails with pointer to incomplete type being passed around (not dereferenced). I am not certain, but I think passing around pointer to incomplete type is a valid thing in C++. I could be wrong though.

```
FAILED: CMakeFiles/lunasvg.dir/source/canvas.cpp.o 
[build] /home/tksuoran/circle_compiler/build_155/circle  -I/home/tksuoran/git/tksuoran/lunasvg/include -I/home/tksuoran/git/tksuoran/lunasvg/source -I/home/tksuoran/git/tksuoran/lunasvg/3rdparty/software -I/home/tksuoran/git/tksuoran/lunasvg/3rdparty/plutovg -g -MD -MT CMakeFiles/lunasvg.dir/source/canvas.cpp.o -MF CMakeFiles/lunasvg.dir/source/canvas.cpp.o.d -o CMakeFiles/lunasvg.dir/source/canvas.cpp.o -c /home/tksuoran/git/tksuoran/lunasvg/source/canvas.cpp
[build] error: /home/tksuoran/git/tksuoran/lunasvg/source/canvas.cpp:135:18
[build] class plutovg_paint is incomplete
[build]   class declared at /home/tksuoran/git/tksuoran/lunasvg/3rdparty/plutovg/plutovg.h:167:9
[build]     plutovg_paint(pluto); 
[build]                  ^
```

**Comment by seanbaxter** [comment]
Thanks for report. That elaborated-type-specifier thing causing the incomplete class error is fixed for the next build.

**Comment by seanbaxter** [comment]
Build 156 is on circle-lang.org and has those two fixes.
