### ISSUE TITLE
Issue with libstdc++ version 11

### ISSUE THREAD

**Issue by tksuoran** [seanbaxter/circle#87]
I am using Ubuntu 20.04 system with `/usr/include/c++/` containing `7`, `7.5.0`, `9`, `11`. I run into issues with the libstdc++11:
```
declaration: /usr/include/c++/11/numbers:138:33
during parsing of std::numbers::e_v initializer
    inline constexpr __float128 e_v<__float128> 
                                ^
  error: /usr/include/c++/11/numbers:139:9
  ... included from /usr/include/c++/11/bits/max_size_type.h:37:10
  ... included from /usr/include/c++/11/bits/ranges_base.h:38:10
  ... included from /usr/include/c++/11/string_view:44:10
  ... included from /usr/include/c++/11/bits/basic_string.h:48:11
  ... included from /usr/include/c++/11/string:55:10
  ... included from /home/tksuoran/git/tksuoran/erhe/src/editor/operations/ioperation.hpp:3:10
  ... included from /home/tksuoran/git/tksuoran/erhe/src/editor/operations/attach_detach_operation.hpp:3:10
  ... included from /home/tksuoran/git/tksuoran/erhe/src/editor/operations/attach_detach_operation.cpp:1:10
  undeclared identifier 'operator""Q'
        = 2.718281828459045235360287471352662498Q; 
          ^
```
Can I somehow choose to use a different version?

**Comment by seanbaxter** [comment]
Ya. `-libstdcxx=10` or `-libstdcxx=10.2` or whatever that folder is named. Did you install libstdc++ 11 from source, or is that supported with Ubuntu's package manager now? I should probably start using that on my dev machine and resolve that issue.

**Comment by seanbaxter** [comment]
```cpp
  template<>
    inline constexpr __float128 e_v<__float128>
      = 2.718281828459045235360287471352662498Q;
```

That bug was me not supporting the 'Q' IEEEquad parsing suffix. This has been added for the next build. Thanks for reporting.

**Comment by tksuoran** [comment]
> Ya. `-libstdcxx=10` or `-libstdcxx=10.2` or whatever that folder is named. Did you install libstdc++ 11 from source, or is that supported with Ubuntu's package manager now? I should probably start using that on my dev machine and resolve that issue.

On Ubuntu 20.04 there is `gcc-11` package which I have installed.
