### ISSUE TITLE
ptxas: "Feature 'activemask' requires PTX ISA .version 6.2 or later" when calling __activemask

### ISSUE THREAD

**Issue by jaredhoberock** [seanbaxter/circle#88]
The program

```
#include <sm_30_intrinsics.hpp>

__global__ void kernel()
{
  int mask = __activemask();
}

int main()
{
  kernel<<<1,1>>>();

  return 0;
}
```

Causes circle to emit the error

```
$ circle --cuda-path=/usr/local/cuda -sm_70 repro.cpp 
ptxas /tmp/circle-tmp-dir-hyAkRh/repro-compute-70.ptx, line 17; error   : Feature 'activemask' requires PTX ISA .version 6.2 or later
ptxas fatal   : Ptx assembly aborted due to errors
fatbinary fatal   : Could not open input file '/tmp/circle-tmp-dir-hyAkRh/repro-sm-70.cubin'
error: could not load fatbin file /tmp/circle-tmp-dir-hyAkRh/repro.fatbin
```

Compiler details:

```
$ circle --version
circle version 1.0.0-155
  Circle public preview build 155
  Built Feb  8 2022 11:15:07
  (c) 2021 Sean Baxter
  https://www.circle-lang.org/
  Twitter: @seanbax
```

I understand that the complaint comes from `ptxas`, but it's not clear to me that I've misused `__activemask` or how to proceed with a solution.

**Comment by seanbaxter** [comment]
Looks like I'm targeting PTX 6.1. Maybe a bump to 7.1 is best, which supports sm_86. https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#changes-in-ptx-isa-version-7-1

Do you have a preference as to which version, or is this something that should be defaulted and set with an optional command line flag?

**Comment by jaredhoberock** [comment]
Thanks for looking into it. I think I'd prefer something like whatever `nvcc` provides.

**Comment by seanbaxter** [comment]
```
  --ptx-version=<value>                     - PTX ISA version number
    =3.2                                    -   PTX ISA version 3.2
    =4.0                                    -   PTX ISA version 4.0
    =4.1                                    -   PTX ISA version 4.1
    =4.2                                    -   PTX ISA version 4.2
    =4.3                                    -   PTX ISA version 4.3
    =5.0                                    -   PTX ISA version 5.0
    =6.0                                    -   PTX ISA version 6.0
    =6.1                                    -   PTX ISA version 6.1
    =6.3                                    -   PTX ISA version 6.3
    =6.4                                    -   PTX ISA version 6.4
    =6.5                                    -   PTX ISA version 6.5
    =7.0                                    -   PTX ISA version 7.0 (default)
```

I don't know if it's configurable in nvcc. Its options are obscure. I added this command line selector. However, LLVM 12 which I'm using tops out at PTX 70/SM 80. I've been passing it the "sm_86" string and it doesn't choke on it, but probably doesn't do any optimizations. Would a bump to LLVM 14 be useful to you, to open up PTX 75/SM 86?

**Comment by jaredhoberock** [comment]
Thanks. At the moment, I'm just trying to get some mgpu code to compile so I have no need for newer SM features right now.

**Comment by seanbaxter** [comment]
Fixed for the next build.
