### ISSUE TITLE
Issues with GSL

### ISSUE THREAD

**Issue by tksuoran** [seanbaxter/circle#93]
Using [GSL](https://github.com/microsoft/GSL) causes issues such as:

```
FAILED: tests/CMakeFiles/gsl_noexcept_tests.dir/no_exception_ensure_tests.cpp.o 
/home/tksuoran/bin/circle  -I/home/tksuoran/git/tksuoran/GSL/include -g -MD -MT tests/CMakeFiles/gsl_noexcept_tests.dir/no_exception_ensure_tests.cpp.o -MF tests/CMakeFiles/gsl_noexcept_tests.dir/no_exception_ensure_tests.cpp.o.d -o tests/CMakeFiles/gsl_noexcept_tests.dir/no_exception_ensure_tests.cpp.o -c /home/tksuoran/git/tksuoran/GSL/tests/no_exception_ensure_tests.cpp
error: /home/tksuoran/git/tksuoran/GSL/include/gsl/span:638:9
... included from /home/tksuoran/git/tksuoran/GSL/tests/no_exception_ensure_tests.cpp:19:10
expected an id-expression
        return {data, data + size(), data}; 
        ^
```
There are also plenty of flags in the `tests/CMakeLists.txt` for GSL that circle does not recognize. GSL can be used as header only library so that is secondary issue.

Circle build 159

**Comment by seanbaxter** [comment]
I just pulled the GSL project and `no_exception_ensure_tests.cpp` doesn't have the line you indicate. Can you point me to it in the current source, or tell me which commit you have checked out?

**Comment by seanbaxter** [comment]
Fixed for the next build. Thanks for reporting.
