### ISSUE TITLE
Extract function signature

### ISSUE THREAD

**Issue by j8asic** [seanbaxter/circle#99]
Why does the following fail to extract the function signature:
```
template<auto F>
struct Signature;

template<typename R, typename... A, R (*F)(A...)>
struct Signature<F> { using ptr = R (*)(A...); };
```
https://godbolt.org/z/adsnM68fv

Moreover, is there a more circe-ly way for function pointers and binding without std stuff?

**Comment by seanbaxter** [comment]
Very nice bug report. Fixed for the next build.

I don't have specific mechanisms on binding. But you can use reflection to get some information about function types:
https://godbolt.org/z/f5hdqdjbG

What kind of binding support did you want to see?

**Comment by j8asic** [comment]
Thanks. I don't have extra requests, just wondering what is currently in. Do you have something prettier for member function pointers than the usual:
```
    (instance.*fn_ptr)(/*...args...*/);
    std::invoke(fn_ptr, instance, /*...args...*/);
```

**Comment by j8asic** [comment]
The above https://godbolt.org/z/adsnM68fv still doesn't work :(

**Comment by seanbaxter** [comment]
Thanks for the report. That's fixed in Build 166. It will be refreshed on compiler explorer overnight. There is still some buggy behavior around pack deduction, but that only shows up in much more complicated use cases.
